.TH YADEX 6 $SOURCE_DATE "Yadex $VERSION" \" -*- nroff -*-
.SH NAME
yadex \- Doom/Doom II/Heretic level (wad) editor for X
.SH SYNOPSIS
.BR "yadex \-?" | \-help | \-\-help
.br
.B yadex \-\-version
.br
\fByadex\fP [\fIoptions\fP] [\fIfile\fP ...]
.SH DESCRIPTION
Yadex can be used to view, create and modify levels for \fBDoom
alpha\fP, \fBDoom press release pre beta\fP, \fBDoom\fP, \fBDoom
II\fP, \fBUltimate Doom\fP, \fBFinal Doom\fP and \fBHeretic\fP.
It also supports, to a lesser extent, \fBHexen\fP and
\fBStrife\fP.

See \fBREADME\fP for a quick start.
.br
To know what's new in this release, see \fBCHANGES\fP.
.br
The rest of documentation is in \fBdoc/index.html\fP (HTML format).
.SH FILES
.TP
.B Configuration file
.B ./yadex.cfg
.br
.BI ~/.yadex/ version /yadex.cfg
.br
.B ~/.yadex/yadex.cfg
.br
.IB install_dir /yadex.cfg
.br
.BI /usr/local/etc/yadex/ version /yadex.cfg
.br
.B /usr/local/etc/yadex/yadex.cfg
.br
.BI /etc/yadex/ version /yadex.cfg
.br
.B /etc/yadex/yadex.cfg
.TP
.B Game definition file
.BI ./ game .ygd
.br
.BI ~/.yadex/ version / game .ygd
.br
.IB install_dir / game .ygd
.br
.BI /usr/local/share/games/yadex/ version / game .ygd
.br
.BI /usr/share/games/yadex/ version / game .ygd
.br
.BI /usr/local/share/games/yadex/ game .ygd
.br
.BI /usr/share/games/yadex/ game .ygd
.SH ENVIRONMENT VARIABLES
.IP \fBDISPLAY\fP
X11 only. The name of the X display that Yadex will try to connect to.
.IP \fBYADEX_GAME\fB
Indicates the game to use.
Overrides the \fBgame\fP parameter in the config file,
is overridden by the \fB\-g\fP command line option.
.SH APPLICATION RESOURCES
None. Yadex does not use the X resources system.
.SH EXIT STATUS
.ta 3
\fB0\fP	OK.
.br
\fB1\fP	Incorrect invocation.
.br
\fB>1\fP	Fatal error.
.SH BUGS
Command line options that take an argument
need to have a space between their argument and themselves.

In certain circumstances, exposures are not handled.
If the Yadex window turns black,
back out by pressing \fBEsc\fP, several times if necessary.

If you edit a level from a file that contains several and save it,
all the other levels from that file are lost.

And many more. See \fBTODO\fP.
.SH AUTHOR
André Majorel <amajorel@teaser.fr>.

Yadex is derived from DEU 5.21 that was written by Raphaël Quinet,
Brendon Wyber and others.

See the HTML documentation for detailed credits.
.SH LEGAL
Yadex incorporates code from DEU 5.21 that was put in the public
domain in 1994 by Raphaël Quinet and Brendon Wyber.

The rest of Yadex is Copyright © 1997-2000 André Majorel.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; if not, write to the Free
Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307, USA.

All trademarks are the propriety of their owners.
.SH SEE ALSO
.BR tkwadcad (6),
.BR xwadtools (6),
.BR ybsp (6)
.IP LDE
http://www-unix.oit.umass.edu/~tetron/lde/
.IP PFME
http://www.purplefrog.com/~thoth/purplefrog/editor.html
.IP "Xwad (part of Dumb)"
http://stekt.oulu.fi/~tosi/dumb/dumb.html
.IP Xwadtools
ftp://ftp.cdrom.com/pub/idgames/source/
