#!/bin/sh
#
#	htmlimg - extract local image names from HTML files
#	AYM 2005-03-18
#

# This file is copyright André Majorel 2005.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of version 2 of the GNU General Public License as published by the
# Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307, USA.


if perl -v >/dev/null 2>/dev/null; then	
  perl -we '							
    use strict;
    use IO::Handle;
    my %imgsrc;
    undef $/;
    while (defined (my $data = <>))
    {
      map { $imgsrc{$_} = undef }
	grep defined $_ && $_ !~ m{^\w+://},
	  $data =~ m/<img\s[^>]*
	    \bsrc=(?:"([[:graph:]]+?)"|([[:graph:]]+?)[\s>])/gix;
    }
    print map "$_\n", sort keys %imgsrc;
    STDOUT->flush or die "htmlimg: (stdout): $!\n";
    unlink "cache/.htmlimg" or die "htmlimg: cache/.htmlimg: $!\n";
    ' "$@"
else
  echo "htmlimg: Perl not installed." >&2
fi
